import { Book, Corrige, SiteSettings, CollectionItem, DisciplineItem, LevelItem, SectionContent } from '@/types';

export const INITIAL_SETTINGS: SiteSettings = {
  site_name: 'Les Éditions Phénix',
  site_tagline: 'La Maison du Succès',
  phone: '07 18 78 40 93 / 07 07 34 49 75 / 05 04 30 37 92',
  whatsapp_number: '2250718784093', // Format international sans '+' pour l'API wa.me
  email: 'contact@editions-phenix.com',
  address: 'Abidjan-Yopougon-Sogefiha solic 2',
  about_text: 'Les Éditions Phénix - La Maison du Succès : maison d\'édition ivoirienne dédiée à l\'accompagnement des élèves, enseignants et établissements scolaires à travers des activités d\'évaluation rigoureuses, des annales d\'examens complètes, des guides méthodologiques éprouvés et des œuvres littéraires captivantes.',
  currency: 'FCFA',
};

export const INITIAL_BOOKS: Book[] = [
  // Collection Succès (Examens & Méthodologie)
  {
    id: 'b1',
    title: 'Code d\'Accès - Annale Histoire-Géographie 3ème (BEPC)',
    slug: 'code-acces-annale-hg-3e',
    author: 'Équipe Pédagogique Phénix',
    category: 'Annales & Examens',
    collection: 'Collection Succès',
    level: '3ème (BEPC)',
    description: 'L\'outil indispensable pour décrocher la mention au BEPC. Regroupe les sujets officiels récents avec corrigés méthodologiques détaillés, barèmes et astuces de rédaction.',
    price: 4000,
    old_price: 4500,
    cover_url: '/covers/code-d-acces-annale-hg-3e.png',
    isbn: '978-2-3849-001-1',
    page_count: 168,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b2',
    title: 'Code d\'Accès - Annale Histoire-Géographie Terminale (BAC)',
    slug: 'code-acces-annale-hg-tle',
    author: 'Inspecteurs & Professeurs Agrégés',
    category: 'Annales & Examens',
    collection: 'Collection Succès',
    level: 'Terminale (BAC A, C, D)',
    description: 'Toutes les clés pour réussir la dissertation et le commentaire de documents au Baccalauréat. Analyses complètes de cartes et graphiques.',
    price: 5000,
    old_price: 5500,
    cover_url: '/covers/code-d-acces-annale-hg-tle.png',
    isbn: '978-2-3849-002-8',
    page_count: 220,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b3',
    title: 'Code d\'Accès - Annale Philosophie Terminale',
    slug: 'code-acces-annale-philo',
    author: 'Dr. Kouassi Étienne',
    category: 'Annales & Examens',
    collection: 'Collection Succès',
    level: 'Terminale (Toutes séries)',
    description: 'Les notions clés décortiquées, plans détaillés de dissertations et explications de texte types avec références canoniques.',
    price: 4500,
    old_price: null,
    cover_url: '/covers/code-d-acces-annale-philo.webp',
    isbn: '978-2-3849-003-5',
    page_count: 196,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b4',
    title: 'Code d\'Accès - Physique-Chimie 3ème',
    slug: 'code-acces-physique-chimie-3eme',
    author: 'M. Touré Brahima & Équipe Sciences',
    category: 'Sciences',
    collection: 'Collection Succès',
    level: '3ème (BEPC)',
    description: 'Synthèse claire des cours, fiches formules mnémotechniques et plus de 200 exercices types d\'examen résolus pas-à-pas.',
    price: 4000,
    old_price: 4500,
    cover_url: '/covers/code-d-acces-physique-chimie-3eme.webp',
    isbn: '978-2-3849-004-2',
    page_count: 180,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b5',
    title: 'Les Secrets du Graphique en Histoire-Géographie',
    slug: 'secret-graphique-hg',
    author: 'Prof. Yapi Sébastien',
    category: 'Méthodologie',
    collection: 'Collection Succès',
    level: 'Lycée (2nde à Tle)',
    description: 'Guide pratique illustré pour maîtriser la lecture, la construction et le commentaire de courbes, diagrammes circulaires et histogrammes aux examens.',
    price: 3500,
    old_price: null,
    cover_url: '/covers/secret-graphique-hg.webp',
    isbn: '978-2-3849-005-9',
    page_count: 120,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b6',
    title: 'Le Répertoire des Citations Philosophiques',
    slug: 'couverture-citations-philo',
    author: 'Dr. Kouassi Étienne',
    category: 'Philosophie',
    collection: 'Collection Succès',
    level: 'Terminale & Supérieur',
    description: 'Plus de 500 citations classées par notion du programme, accompagnées de leur contexte, interprétation et exemples d\'utilisation en dissertation.',
    price: 3500,
    old_price: 4000,
    cover_url: '/covers/couverture-citations-philo.webp',
    isbn: '978-2-3849-006-6',
    page_count: 144,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },

  // Collection Archives (Cahiers d'Activités & Évaluation Histoire-Géo)
  {
    id: 'b7',
    title: 'Histoire-Géographie 6ème - Activités d\'Évaluation & Exercices',
    slug: 'hg-manuel-6e',
    author: 'Collectif d\'Enseignants du Secondaire',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Classe de 6ème',
    description: 'Cahier complet d\'activités d\'évaluation et d\'exercices conformes aux programmes officiels. Évaluation continue, études de documents et repères spatio-temporels.',
    price: 4500,
    old_price: null,
    cover_url: '/covers/hg-couverture-6e-1ere-couv.webp',
    isbn: '978-2-3849-010-3',
    page_count: 192,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b8',
    title: 'Histoire-Géographie 5ème - Activités d\'Évaluation & Exercices',
    slug: 'hg-manuel-5e',
    author: 'Collectif d\'Enseignants du Secondaire',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Classe de 5ème',
    description: 'Activités d\'apprentissage et fiches d\'évaluation formative. Les grands empires africains, le Moyen Âge et dynamiques démographiques.',
    price: 4500,
    old_price: null,
    cover_url: '/covers/hg-couverture-5e-1ere-couv.webp',
    isbn: '978-2-3849-011-0',
    page_count: 204,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b9',
    title: 'Histoire-Géographie 4ème - Activités d\'Évaluation & Exercices',
    slug: 'hg-manuel-4e',
    author: 'Collectif d\'Enseignants du Secondaire',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Classe de 4ème',
    description: 'Traite négrière, révolutions industrielles, géographie humaine et économique. Fiches méthodes d\'évaluation intégrées.',
    price: 4800,
    old_price: null,
    cover_url: '/covers/hg-couverture-4e-1ere-couv.webp',
    isbn: '978-2-3849-012-7',
    page_count: 216,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b10',
    title: 'Histoire-Géographie 3ème - Activités d\'Évaluation (BEPC)',
    slug: 'hg-manuel-3e',
    author: 'Collectif d\'Enseignants du Secondaire',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Classe de 3ème (BEPC)',
    description: 'Cahier d\'entraînement intensif et d\'évaluation pour la préparation au BEPC. Sujets d\'entraînement, devoirs surveillés types et repères méthodologiques.',
    price: 5000,
    old_price: 5500,
    cover_url: '/covers/hg-couverture-3e-1ere-couv.webp',
    isbn: '978-2-3849-013-4',
    page_count: 232,
    published_year: 2024,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b11',
    title: 'Histoire-Géographie 2nde - Activités d\'Évaluation & Documents',
    slug: 'hg-manuel-2nde',
    author: 'Collectif d\'Inspecteurs Pédagogiques',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Classe de Seconde',
    description: 'Initiation à l\'analyse documentaire avancée, évaluations sur les espaces mondialisés et grands courants historiques.',
    price: 5500,
    old_price: null,
    cover_url: '/covers/hg-couverture-2nde-1ere-couv.webp',
    isbn: '978-2-3849-014-1',
    page_count: 240,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b12',
    title: 'Histoire-Géographie 1ère - Activités d\'Évaluation & Méthodologie',
    slug: 'hg-manuel-1ere',
    author: 'Collectif d\'Inspecteurs Pédagogiques',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Classe de Première',
    description: 'Étude critique de documents historiques et cartographiques, évaluations formatives préparatoires aux épreuves du Baccalauréat.',
    price: 5500,
    old_price: null,
    cover_url: '/covers/hg-couverture-1ere-1ere-couv.webp',
    isbn: '978-2-3849-015-8',
    page_count: 256,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b13',
    title: 'Histoire-Géographie Terminale - Activités d\'Évaluation & Devoirs Types (BAC)',
    slug: 'hg-manuel-tle',
    author: 'Inspecteurs & Professeurs Certifiés',
    category: 'Activités d\'Évaluation',
    collection: 'Collection Archives',
    level: 'Terminale (Toutes séries)',
    description: 'L\'outil indispensable pour les épreuves du Baccalauréat. Dissertations guidées, commentaires de documents et graphiques commentés.',
    price: 6000,
    old_price: 6500,
    cover_url: '/covers/hg-couverture-tle-1ere-couv.webp',
    isbn: '978-2-3849-016-5',
    page_count: 272,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },

  // Collection Polyglotte (Anglais)
  {
    id: 'b14',
    title: 'English Oral Skills for BEPC',
    slug: 'anglais-oral-bepc',
    author: 'Kouamé N\'Dri & English Dept.',
    category: 'Langues Vivantes',
    collection: 'Collection Polyglotte',
    level: '3ème (BEPC)',
    description: 'Guide interactif pour réussir avec aisance l\'épreuve orale d\'anglais au BEPC. Fiches de vocabulaire thématique, dialogues modèles et questions types.',
    price: 3500,
    old_price: 4000,
    cover_url: '/covers/anglais-oral-bepc.png',
    isbn: '978-2-3849-020-2',
    page_count: 140,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b15',
    title: 'English Oral Mastery for BAC',
    slug: 'anglais-oral-bac',
    author: 'Kouamé N\'Dri & English Dept.',
    category: 'Langues Vivantes',
    collection: 'Collection Polyglotte',
    level: 'Terminale (BAC)',
    description: 'Techniques d\'expression orale fluide, analyse d\'articles et débats d\'actualité pour briller devant les jurys d\'examen du Baccalauréat.',
    price: 4000,
    old_price: 4500,
    cover_url: '/covers/anglais-oral-bac.png',
    isbn: '978-2-3849-021-9',
    page_count: 160,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b16',
    title: 'English Grammar & Vocabulary (6e - 5e)',
    slug: 'anglais-6e-5e',
    author: 'Mrs. Sarah Kone',
    category: 'Langues Vivantes',
    collection: 'Collection Polyglotte',
    level: '6ème & 5ème',
    description: 'Méthode ludique et communicative pour construire des bases solides en anglais dès le premier cycle.',
    price: 3500,
    old_price: null,
    cover_url: '/covers/anglais-6e-5e.png',
    isbn: '978-2-3849-022-6',
    page_count: 128,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b17',
    title: 'Mastering English Writing & Essay',
    slug: 'anglais-writing',
    author: 'Mr. David Olatunde',
    category: 'Langues Vivantes',
    collection: 'Collection Polyglotte',
    level: 'Second cycle (Lycée)',
    description: 'Apprendre à rédiger des essais convaincants, des lettres formelles et des synthèses de textes en langue anglaise.',
    price: 4000,
    old_price: null,
    cover_url: '/covers/anglais-writing.png',
    isbn: '978-2-3849-023-3',
    page_count: 152,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },

  // Collection Papyrus (Littérature générale & Romans)
  {
    id: 'b18',
    title: 'Soir d\'un Monde (Roman)',
    slug: 'soir-dun-monde',
    author: 'Aimé C. Tanoh',
    category: 'Littérature & Romans',
    collection: 'Collection Papyrus',
    level: 'Tout public / Lycée',
    description: 'Une œuvre poignante sur la mémoire, le déchirement entre traditions ancestrales et vertige de la modernité urbaine dans une Afrique en pleine métamorphose.',
    price: 4500,
    old_price: null,
    cover_url: '/covers/soir-d-un-monde.webp',
    isbn: '978-2-3849-030-1',
    page_count: 224,
    published_year: 2024,
    is_featured: true,
    in_stock: true,
  },
  {
    id: 'b19',
    title: 'La Poule aux Œufs Dort (Conte & Récit)',
    slug: 'la-poule-aux-oeufs-dort',
    author: 'Clarisse Bamba',
    category: 'Littérature & Jeunesse',
    collection: 'Collection Papyrus',
    level: 'Collège & Jeunesse',
    description: 'Une fable satirique et drôle qui éveillera l\'esprit critique et l\'amour de la lecture chez les jeunes lecteurs.',
    price: 3000,
    old_price: 3500,
    cover_url: '/covers/la-poule-aux-oeufs-dort.webp',
    isbn: '978-2-3849-031-8',
    page_count: 112,
    published_year: 2024,
    is_featured: true,
    in_stock: true,
  },

  // Collection École et Métiers (CMC)
  {
    id: 'b20',
    title: 'Communication & Méthodes Commerciales (CMC) 2nde',
    slug: 'couverture-cmc-2nde',
    author: 'Département Tertiaire Phénix',
    category: 'Filières Tertiaires',
    collection: 'Collection École et Métiers',
    level: 'Seconde G1/G2/AB',
    description: 'Guide pratique et activités conformes aux programmes techniques et professionnels. Fondements de la communication en entreprise et des techniques administratives.',
    price: 5000,
    old_price: null,
    cover_url: '/covers/couverture-cmc-2nde-1ere-couv.webp',
    isbn: '978-2-3849-040-0',
    page_count: 180,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b21',
    title: 'Communication & Méthodes Commerciales (CMC) 1ère',
    slug: 'couverture-cmc-1ere',
    author: 'Département Tertiaire Phénix',
    category: 'Filières Tertiaires',
    collection: 'Collection École et Métiers',
    level: 'Première G1/G2/AB',
    description: 'Gestion de dossiers clients, correspondance professionnelle moderne et traitement informatisé de données d\'entreprise.',
    price: 5500,
    old_price: null,
    cover_url: '/covers/couverture-cmc-1ere-1ere-couv.webp',
    isbn: '978-2-3849-041-7',
    page_count: 210,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  {
    id: 'b22',
    title: 'Communication & Méthodes Commerciales (CMC) Terminale',
    slug: 'couverture-cmc-tle',
    author: 'Département Tertiaire Phénix',
    category: 'Filières Tertiaires',
    collection: 'Collection École et Métiers',
    level: 'Terminale G1/G2/AB (BAC)',
    description: 'Préparation intensive aux épreuves pratiques et écrites du BAC Technique. Études de cas réelles et corrigés types.',
    price: 6000,
    old_price: 6500,
    cover_url: '/covers/couverture-cmc-tle-1ere-couv.webp',
    isbn: '978-2-3849-042-4',
    page_count: 240,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  },

  // Collection Racines (Français & Dictée-Questions)
  {
    id: 'b23',
    title: 'Dictée - Questions & Analyse de Texte (Collège)',
    slug: 'couverture-dq-college',
    author: 'Équipe Pédagogique Lettres',
    category: 'Français & Langues',
    collection: 'Collection Racines',
    level: 'Collège (6e à 3e)',
    description: 'Recueil de 150 textes choisis avec questions de compréhension, vocabulaire, grammaire et corrigés intégraux.',
    price: 3500,
    old_price: null,
    cover_url: '/covers/couverture-dq-1ere-couv.webp',
    isbn: '978-2-3849-050-9',
    page_count: 160,
    published_year: 2024,
    is_featured: false,
    in_stock: true,
  },
  // Collection Jeune Citoyen (EDHC & Civisme)
  {
    id: 'b24',
    title: 'Éducation aux Droits de l\'Homme et Citoyenneté (EDHC) - Guide du Jeune Citoyen',
    slug: 'edhc-guide-jeune-citoyen',
    author: 'Comité Éthique & Civisme Phénix',
    category: 'Civisme & EDHC',
    collection: 'Collection Jeune Citoyen',
    level: 'Collège & Lycée',
    description: 'Manuel pratique d\'initiation aux droits humains, à la paix, au respect des institutions républicaines et à la citoyenneté responsable.',
    price: 3500,
    old_price: 4000,
    cover_url: '/covers/code-d-acces-annale-hg-3e.png',
    isbn: '978-2-3849-060-8',
    page_count: 144,
    published_year: 2025,
    is_featured: true,
    in_stock: true,
  }
];

export const INITIAL_CORRIGES: Corrige[] = [
  {
    id: 'c1',
    book_id: 'b1',
    book_title: 'Code d\'Accès - Annale Histoire-Géographie 3ème (BEPC)',
    title: 'Corrigé Officiel - Annale Histoire-Géographie 3ème (Sujets 1 à 6)',
    description: 'Corrigés complets et rédactions modèles des sujets d\'examen du premier tome. Conforme aux barèmes officiels.',
    subject: 'Histoire-Géographie',
    level: '3ème (BEPC)',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'Corrige_Officiel_HG_3e_BEPC.pdf',
    file_type: 'pdf',
    file_size: '2.1 Mo',
    download_count: 342,
  },
  {
    id: 'c2',
    book_id: 'b2',
    book_title: 'Code d\'Accès - Annale Histoire-Géographie Terminale (BAC)',
    title: 'Corrigé Type - Dissertation & Commentaire de Cartes BAC',
    description: 'Plans détaillés, introductions et conclusions rédigées pour les 8 sujets de synthèse du manuel.',
    subject: 'Histoire-Géographie',
    level: 'Terminale (BAC)',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'Corrige_BAC_HG_Terminale_Synthese.docx',
    file_type: 'docx',
    file_size: '950 Ko',
    download_count: 512,
  },
  {
    id: 'c3',
    book_id: 'b3',
    book_title: 'Code d\'Accès - Annale Philosophie Terminale',
    title: 'Corrigés Types - 10 Dissertations Philosophiques Majeures',
    description: 'Rédaction intégrale de dissertations sur la Conscience, l\'État, la Liberté et la Vérité avec citations expliquées.',
    subject: 'Philosophie',
    level: 'Terminale',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'Corriges_Dissertations_Philo_Terminale.pdf',
    file_type: 'pdf',
    file_size: '1.7 Mo',
    download_count: 428,
  },
  {
    id: 'c4',
    book_id: 'b4',
    book_title: 'Code d\'Accès - Physique-Chimie 3ème',
    title: 'Corrigé des Exercices de Synthèse - Physique-Chimie 3ème',
    description: 'Solutions numériques détaillées, calculs d\'énergie, équations-bilans chimiques et tracés de circuits.',
    subject: 'Physique-Chimie',
    level: '3ème (BEPC)',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'Corrige_Exercices_Physique_Chimie_3e.pdf',
    file_type: 'pdf',
    file_size: '3.4 Mo',
    download_count: 610,
  },
  {
    id: 'c5',
    book_id: 'b14',
    book_title: 'English Oral Skills for BEPC',
    title: 'Audio Scripts & Answer Key - English Oral BEPC',
    description: 'Transcriptions complètes des dialogues et corrigés types des questions posées lors de l\'épreuve orale.',
    subject: 'Anglais',
    level: '3ème (BEPC)',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'BEPC_English_Oral_Answer_Key.pdf',
    file_type: 'pdf',
    file_size: '1.2 Mo',
    download_count: 289,
  },
  {
    id: 'c6',
    book_id: 'b22',
    book_title: 'Communication & Méthodes Commerciales (CMC) Terminale',
    title: 'Corrigé Études de Cas - CMC Terminale G1 & G2',
    description: 'Modèles de lettres commerciales, grilles d\'évaluation et résolution des études de cas de gestion administrative.',
    subject: 'CMC / Tertiaire',
    level: 'Terminale G1/G2',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'Corrige_Cas_Pratiques_CMC_Tle.docx',
    file_type: 'docx',
    file_size: '1.4 Mo',
    download_count: 175,
  },
  {
    id: 'c7',
    book_id: 'b23',
    book_title: 'Dictée - Questions & Analyse de Texte (Collège)',
    title: 'Corrigé Intégral des 50 Textes de Dictée-Questions',
    description: 'Règles d\'accord orthographiques explicitées, analyse grammaticale et corrigé des questions de compréhension.',
    subject: 'Français',
    level: 'Collège',
    file_url: 'https://raw.githubusercontent.com/mozilla/pdf.js/master/web/compressed.tracemonkey-pldi-09.pdf',
    file_name: 'Corrige_Dictee_Questions_College.pdf',
    file_type: 'pdf',
    file_size: '2.8 Mo',
    download_count: 380,
  }
];

export const INITIAL_COLLECTIONS: CollectionItem[] = [
  {
    id: 'col-1',
    name: 'Collection Archives',
    description: 'Cahiers d\'activités d\'évaluation et situations d\'apprentissage (Histoire-Géo)',
    color: 'from-blue-600 to-blue-800',
  },
  {
    id: 'col-2',
    name: 'Collection École et Métiers',
    description: 'Filières professionnelles tertiaires et Communication & Méthodes Commerciales (CMC)',
    color: 'from-teal-600 to-teal-800',
  },
  {
    id: 'col-3',
    name: 'Collection Jeune Citoyen',
    description: 'Éducation aux Droits de l\'Homme, Citoyenneté (EDHC), civisme et paix',
    color: 'from-amber-500 to-orange-700',
  },
  {
    id: 'col-4',
    name: 'Collection Succès',
    description: 'Annales officielles et méthodologies intensives pour examens (BEPC & BAC)',
    color: 'from-amber-600 to-amber-800',
  },
  {
    id: 'col-5',
    name: 'Collection Polyglotte',
    description: 'Guides d\'apprentissage des langues vivantes et compétences orales (Anglais)',
    color: 'from-emerald-600 to-emerald-800',
  },
  {
    id: 'col-6',
    name: 'Collection Racines',
    description: 'Patrimoine culturel, dictée-questions, grammaire et analyse littéraire',
    color: 'from-rose-600 to-rose-800',
  },
  {
    id: 'col-7',
    name: 'Collection Papyrus',
    description: 'Romans, poésie et créations littéraires ivoiriennes et africaines',
    color: 'from-purple-600 to-purple-800',
  },
];

export const INITIAL_DISCIPLINES: DisciplineItem[] = [
  { id: 'disc-1', name: 'Histoire-Géographie', description: 'Histoire, Géographie, Géopolitique et Éducation aux Droits de l\'Homme' },
  { id: 'disc-2', name: 'Mathématiques', description: 'Calcul, Algèbre, Géométrie et Analyse' },
  { id: 'disc-3', name: 'Philosophie', description: 'Dissertation philosophique et explication de texte méthodique' },
  { id: 'disc-4', name: 'Physique-Chimie', description: 'Sciences physiques, chimie organique et mécanique' },
  { id: 'disc-5', name: 'Anglais', description: 'Compréhension de texte, grammaire et expression orale' },
  { id: 'disc-6', name: 'Français', description: 'Grammaire, orthographe, dictée, commentaire et contraction de texte' },
  { id: 'disc-7', name: 'Sciences de la Vie et de la Terre (SVT)', description: 'Biologie, géologie et sciences environnementales' },
  { id: 'disc-8', name: 'Communication & Commerce (CMC)', description: 'Filières tertiaires, correspondance commerciale et gestion' },
  { id: 'disc-9', name: 'Civisme & EDHC', description: 'Éducation aux droits de l\'homme et à la citoyenneté' },
  { id: 'disc-10', name: 'Littérature & Romans', description: 'Œuvres littéraires, théâtre et poésie' },
];

export const INITIAL_LEVELS: LevelItem[] = [
  { id: 'lvl-1', name: '6ème', cycle: 'Collège', order_index: 1 },
  { id: 'lvl-2', name: '5ème', cycle: 'Collège', order_index: 2 },
  { id: 'lvl-3', name: '4ème', cycle: 'Collège', order_index: 3 },
  { id: 'lvl-4', name: '3ème (BEPC)', cycle: 'Collège', order_index: 4 },
  { id: 'lvl-5', name: '2nde', cycle: 'Lycée', order_index: 5 },
  { id: 'lvl-6', name: '1ère', cycle: 'Lycée', order_index: 6 },
  { id: 'lvl-7', name: 'Terminale (BAC)', cycle: 'Lycée', order_index: 7 },
  { id: 'lvl-8', name: 'Collège & Lycée', cycle: 'Secondaire', order_index: 8 },
  { id: 'lvl-9', name: 'Tout public', cycle: 'Général', order_index: 9 },
];

export const INITIAL_SECTIONS: SectionContent[] = [
  {
    id: 'sec-hero',
    section_key: 'hero',
    badge: 'Les Éditions Phénix — La Maison du Succès',
    title: 'La Maison du Succès pour vos Examens et Évaluations',
    subtitle: 'Découvrez les cahiers d\'activités d\'évaluation, annales méthodologiques (BEPC, BAC), guides pratiques et créations littéraires de Les Éditions Phénix.',
    description: 'Explorez la Collection Archives et toutes nos séries conformes aux programmes officiels.',
  },
  {
    id: 'sec-catalogue',
    section_key: 'catalogue',
    badge: 'Catalogue Officiel — La Maison du Succès',
    title: 'Nos Activités d\'Évaluation, Annales & Guides',
    subtitle: 'Explorez l\'ensemble des titres édités par Les Éditions Phénix : cahiers d\'activités d\'évaluation, guides méthodologiques, annales d\'examens (BEPC, BAC) et œuvres littéraires.',
  },
  {
    id: 'sec-corriges',
    section_key: 'corriges',
    badge: 'Ressource 100% Gratuite',
    title: 'Téléchargez Librement les Corrigés Officiels',
    subtitle: 'Pour soutenir les élèves et les enseignants, Les Éditions Phénix mettent à disposition les corrigés complets de tous les devoirs et annales au format PDF et Word.',
  },
  {
    id: 'sec-revendeurs',
    section_key: 'revendeurs',
    badge: 'Espace Professionnel • Librairies, Écoles & Grossistes',
    title: 'Bon de Commande & Point des Documents',
    subtitle: 'Bienvenue dans l\'espace réservé aux établissements scolaires, librairies partenaires et revendeurs des Éditions Phénix. Transmettez directement votre bordereau de commande sans intermédiaire.',
  },
  {
    id: 'sec-apropos',
    section_key: 'a_propos',
    badge: 'Les Éditions Phénix — La Maison du Succès',
    title: 'La Maison du Succès : Élever le Savoir et Réussir les Examens',
    subtitle: 'Fondée avec la passion d\'instruire et d\'élever, Les Éditions Phénix conçoivent des outils d\'apprentissage pragmatiques pour les élèves, enseignants et passionnés de lettres.',
  },
];

